openapi: 3.0.0
info:
  title: API de Comunicados
  version: 1.0.0
paths:

  /trainingpro/v1/comms/all-comms:
    get:
      tags:
        - Comunications
      summary: Mostrar comunicados
      responses:
        '200':
          description: Listado de tipos de dirección.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      example: "67868ab3c69cb35b43c45f58"
                    email:
                      type: string
                      example: "trainingpro@gmail.com"
                    text:
                      type: string
                      example: "cualquiera"
                    complaints:
                      type: string
                      example: "queja1"
  
  /trainingpro/v1/comms/new-comm:
    post:
      tags:
        - Comunications
      summary: Crear un nuevo comunicado
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "nono@gmail.com"
                text:
                  type: string
                  example: "Text example"
                complaints:
                  type: string
                  example: "Complaint example"
      responses:
        '200':
          description: Nuevo comunicado creado
          content:
            application/json:
              schema:
                type: string
                example: 'Documento insertado con ID: 67a4fc26cdf4b10feab0641a'